auto: true
pygments: true
title: ianreah.com
description: 
paginate: 5
navigable-pages:
  - title: home
    url: /index.html
  - title: projects
    url: /projects.html
  - title: about
    url: /about.html